### ISSUE TITLE
Wrath Classic (3.4.1) scanning tooltip improvement

### ISSUE THREAD

**Issue by Road-block** [itsSinba/SinStats#7]
Since 3.4.1 _some_ of the old style scanning tooltips cause issues with default game tooltips that are on a perpetually refreshing timer (examples: temporary weapon enchant tooltips for rogue:poison/shaman:imbues/warlock:spellstones, items with a temporary tradeable timer, buff tooltips etc)

A scanning tooltip parented to UIParent or with UIParent as its owner causes artifacts on those kinds of tooltips: misaligned text, blank or  expanding text.

The more often scanTooltip:Set<X> is called the more pronounced the effect.

The way to solve this is to avoid creating the scanning tooltip with a UIParent parent and SetOwner to WorldFrame instead.

The relevant changes to SinStats are: 
SinStats\Stats\Wrath\Misc.lua:8 to
```lua
local repairTooltip = CreateFrame("GameTooltip", "SinStatsTooltip", nil, "GameTooltipTemplate")
repairTooltip:SetOwner(WorldFrame, "ANCHOR_NONE")
```
and 
SinStats\Stats\Classic\Misc.lua:8 to
```lua
local repairTooltip = CreateFrame("GameTooltip", "SinStatsTooltipClassic", nil, "GameTooltipTemplate")
repairTooltip:SetOwner(WorldFrame, "ANCHOR_NONE")
```
This will keep the scanning tooltips working without causing artifacts to refreshing default game tooltips.

**Comment by itsSinba** [comment]
Thanks for your input Road-block. It definitely makes sense, I will implement it in the next update. Cheers
