### ISSUE TITLE
Wrath Classic (3.4.1) Blood gorged counting as 20% arpen should be 10%

### ISSUE THREAD

**Issue by danniellos94** [itsSinba/SinStats#8]
As in the title Blood gorged (wotlk classic) counting as 20% arpen should be 10%
https://prnt.sc/lUfFM-I504cj

**Comment by itsSinba** [comment]
Hi daniellos. After verification, Blood Gorged is a calculated properly. Digging a little deeper, I noticed a bug where a warrior's 10% arp from Battle Stance was added to a DK's Blood Presence (they share the same stance number).

It's fixed and will be pushed in the next update (5.1.1).

I appreciate you reporting the bug. Cheers
